services:
  docs:
    image: graffiti_wall_local_docs
    container_name: graffiti_wall_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./graffiti_wall:/app/graffiti_wall:z
    ports:
      - '9000:9000'
    command: /start-docs
